### ISSUE TITLE
Upload weights file.

### ISSUE THREAD

**Issue by akashdeepjassal** [RockyXu66/Faster_RCNN_for_Open_Images_Dataset_Keras#2]
Hey, I find this repository interesting.
it would be nice if you upload weight files.

**Comment by RockyXu66** [comment]
Hi. Do you mean the weight files I trained for ‘Car’, ‘Person’ and ‘Mobile phone’? I just saved them in Google Drive after training. This is the [link](https://drive.google.com/open?id=1FoKDz5N_PZUwcBu1DzjnD7t7c3w5v37p) if you need.

**Comment by akashdeepjassal** [comment]
Thank you
