### ISSUE TITLE
When I run data_gen_train,I got Infinite loop?

### ISSUE THREAD

**Issue by mohhao** [RockyXu66/Faster_RCNN_for_Open_Images_Dataset_Keras#28]
It's strange, man

**Comment by williamgun007** [comment]
@mohhao you have already solve this issue ?

**Comment by kshitiz-ds** [comment]
hello I also have the same issue. Can you help how to solve it. 
i am using my own dataset related to fashion and i am using just 570 images in total and even after that it is running for more than 9 hours,

**Comment by williamgun007** [comment]
It work after I change exception inside looping from `continue` to `break`.
