### ISSUE TITLE
Object Detection DataPreprocessing error KeyError: <class 'numpy.object_'>

### ISSUE THREAD

**Issue by pendex900x** [RockyXu66/Faster_RCNN_for_Open_Images_Dataset_Keras#39]
When I try to download the subclassfile.csv images to a folder, it give me this error at seccion "Download Images":

```
# Download images
for i in range(len(classes)):
    # Create the directory
    os.mkdir(saved_dirs[i])
    saved_dir = saved_dirs[i]
    for url in urls[i]:
        #print(url)
        img = io.imread(url)
        saved_path = os.path.join(saved_dir, url[-20:])
        io.imsave(saved_path, img)
```

```
WARNING: Logging before flag parsing goes to stderr.
W1205 05:46:35.025649 139647583152000 module_wrapper.py:139] From /usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/api/_v1/estimator/__init__.py:12: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.inputs instead.


KeyErrorTraceback (most recent call last)
<ipython-input-25-a51579775e1b> in <module>()
      7         img = io.imread(url)
      8         saved_path = os.path.join(saved_dir, url[-20:])
----> 9         io.imsave(saved_path, img)

2 frames
/usr/local/lib/python2.7/dist-packages/skimage/util/dtype.pyc in dtype_limits(image, clip_negative)
     55         warn('The default of `clip_negative` in `skimage.util.dtype_limits` '
     56              'will change to `False` in version 0.15.')
---> 57     imin, imax = dtype_range[image.dtype.type]
     58     if clip_negative:
     59         imin = 0

KeyError: <type 'numpy.object_'>
```

Then I read that you found a good solution with [OIDv4_ToolKit](https://github.com/EscVM/OIDv4_ToolKit) but I cant implement it (maybe it's because there is another updated version).
There is another way to fix this? thanks! you made an excelent work.

**Comment by pendex900x** [comment]
# Download images
for i in range(len(classes)):
    # Create the directory
    os.mkdir(saved_dirs[i])
    saved_dir = saved_dirs[i]
    for url in urls[i]:
        #print(url)
        img = io.imread(url)
        saved_path = os.path.join(saved_dir, url[-20:])
        **if img.shape[0] == 2:
               img = img[0]**
        io.imsave(saved_path, img)

this 2 lines fixed, I spent arround all day to this. Hope to help those who need it

**Comment by PeymanBaghdadi** [comment]
Hey @pendex900x  can you help me through my issue #55
It is about directories in google colab and upload which file where!! I misunderstood.
