### ISSUE TITLE
Error: <Could not load pretrained model weights> ocurred while executing frcnn_train_vgg.ipynb 

### ISSUE THREAD

**Issue by Aman3593** [RockyXu66/Faster_RCNN_for_Open_Images_Dataset_Keras#4]
While training the model, I facing problem of loading the VGG_16_weights(pretrained).

As per suggestion, First I have downloaded 'vgg16_weights_tf_dim_ordering_tf_kernels.h5' from keras application folder. 

Below is the code for downloading:

from keras.applications.vgg16 import VGG16
# load the model
model = VGG16()

Output:
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels.h5
553467904/553467096 [==============================] - 529s 1us/step

As you can see from the output, I have successfully downloaded the weights.

But when I loaded the weights for training I got the following error:
<
This is the first time of your training
loading weights from Downloads/Faster_RCNN/model/vgg16_weights_tf_dim_ordering_tf_kernels.h5
Could not load pretrained model weights. Weights can be found in the keras application folder             https://github.com/fchollet/keras/tree/master/keras/applications
>
My given path is also correct.
I have  also checked multiple times for the path which I have provided but couldn't find anything wrong. 

Please help me solving this problem.

**Comment by PeymanBaghdadi** [comment]
Hey @Aman3593  can you help me through my issue #55
It is about directories in google colab and upload which file where!! I misunderstood.
