### ISSUE TITLE
AttributeError: <module 'keras.backend' has no attribute 'image_dim_ordering'> occurred while frcnn_train_vgg.ipynb

### ISSUE THREAD

**Issue by Boosby** [RockyXu66/Faster_RCNN_for_Open_Images_Dataset_Keras#48]
While trying to run the **# define the RPN, built on the base layers** code block from the **frcnn_train_vgg.ipynb** I get the error mentioned in the title. 
<img width="950" alt="Screenshot" src="https://user-images.githubusercontent.com/44981815/78681684-582abe80-78ed-11ea-876c-9091a4f14796.png">

**Comment by Boosby** [comment]
Found the solution:
Use **K.common.image_dim_ordering()**
instead of **K.image_dim_ordering()**

**Comment by PeymanBaghdadi** [comment]
Hey @Boosby  can you help me through my issue #55
It is about directories in google colab and upload which file where!! I misunderstood.

**Comment by adavradou** [comment]
**Update**: 
According to [this](https://github.com/keras-team/keras/issues/12649), in keras v2 the `image_dim_ordering()` has been replaced by `image_data_format()`.

Thus I changed the code to: 
`self.dim_ordering = K.image_data_format()`

Hope it helps, cheers!
