### ISSUE TITLE
about colab in frcnn_train_vgg.ipynb

### ISSUE THREAD

**Issue by PeymanBaghdadi** [RockyXu66/Faster_RCNN_for_Open_Images_Dataset_Keras#55]
After I go deeper I did this:
In my google drive I create these directories:
drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/
drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/test/
drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/train/
drive/My Drive/AI/Dataset/Faster_RCNN/
Then I upload "annotation.txt" , "test_annotation.txt", "test.csv", "train.csv" into "drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/".
I also upload images within train folder into "drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/train/" directory and upload images within test folder into "drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/test/".
My "drive/My Drive/AI/Dataset/Faster_RCNN/" directory is empty, because I understood that the results must be place within this directory.
I misunderstood the part of VGG-16 pretrained model:
output_weight_path = os.path.join(base_path, 'model/model_frcnn_vgg.hdf5')
record_path = os.path.join(base_path, 'model/record.csv') # Record data (used to save the losses, classification accuracy and mean average precision)
base_weight_path = os.path.join(base_path, 'model/vgg16_weights_tf_dim_ordering_tf_kernels.h5')
config_output_filename = os.path.join(base_path, 'model_vgg_config.pickle')
Should I get it from somewhere or the program make it, itself. 
Anyway I run the code into google colab and get this error.
Please someone help me where I do wrong and what should I fix or done more.
I am a PHD student that have a project and I am really need to run this project.
![colab_probjpg_03](https://user-images.githubusercontent.com/63775142/79556530-e4857000-80a9-11ea-87ba-916b76cc6d93.jpg)

**Comment by PeymanBaghdadi** [comment]
I do follow jobs:
I go to the link and get the autherization code and paste it. Then I make the path like the @RockyXu66  as below:
drive/My Drive/AI/Dataset/
Then I upload all the train folder, test folder, annotation.txt, test_annotation.txt, test.csv and train.csv files. Then I Run all the codes in colab and get the error in picture.
I think my problem is due to paths in my google drive, Please someone help me to fix this.
1. What paths I should have in my drive.
2. Which files I should upload to which path.
3. I need above step by step explanation.
![colab_probjpg_02](https://user-images.githubusercontent.com/63775142/79462790-a7b16e80-8000-11ea-93e1-072263e2568a.jpg)

**Comment by PeymanBaghdadi** [comment]
After I go deeper I did this:
In my google drive I create these directories:
drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/
drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/test/
drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/train/
drive/My Drive/AI/Dataset/Faster_RCNN/
Then I upload "annotation.txt" , "test_annotation.txt", "test.csv", "train.csv" into "drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/".
I also upload images within train folder into "drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/train/" directory and upload images within test folder into "drive/My Drive/AI/Dataset/Open Images Dataset v4 (Bounding Boxes)/test/".
My "drive/My Drive/AI/Dataset/Faster_RCNN/" directory is empty, because I understood that the results must be place within this directory.
I misunderstood the part of VGG-16 pretrained model:
output_weight_path = os.path.join(base_path, 'model/model_frcnn_vgg.hdf5')
record_path = os.path.join(base_path, 'model/record.csv') # Record data (used to save the losses, classification accuracy and mean average precision)
base_weight_path = os.path.join(base_path, 'model/vgg16_weights_tf_dim_ordering_tf_kernels.h5')
config_output_filename = os.path.join(base_path, 'model_vgg_config.pickle')
Should I get it from somewhere or the program make it, itself. 
Anyway I run the code into google colab and get this error.
Please someone help me where I do wrong and what should I fix or done more.
I am a PHD student that have a project and I am really need to run this project.
![colab_probjpg_03](https://user-images.githubusercontent.com/63775142/79556530-e4857000-80a9-11ea-87ba-916b76cc6d93.jpg)

**Comment by Boosby** [comment]
The path of your "/Faster_RCNN" folder is incorrect. It needs to be as follow: "drive/My Drive/AI/Faster_RCNN/"
And you also need this path: "drive/My Drive/AI/Faster_RCNN/model"
Your test.csv and train.csv files are not needed but actually that doesn't't matter, you can leave them in.
The 'model_vgg_config.pickle' file will be created by the program itself.

Edit: And you need to rename the .txt files like this:
test_annotations.txt (rename this to person_car_phone_test_annotation.txt)
annotations.txt (rename this to person_car_phone_train_annotation.txt)

**Comment by PeymanBaghdadi** [comment]
Thank you @Boosby I make the directories correct, also instead of changing annotation files name, I changed them in the code, But my problem is related to :
(row,cols) = img.shape[:2]
Bu the way my project is as same as @RockyXu66 (car, person, phone) but I only get 100 sample instead of 1000. I stuck in frcnn_train_vgg.ipynb . :(

**Comment by PeymanBaghdadi** [comment]
I solved it, it was because of my path within annotation.txt and test_annotation.txt.
I should change last \ with /. the problem has been solved

**Comment by amaranth-andi** [comment]
> I solved it, it was because of my path within annotation.txt and test_annotation.txt.
> I should change last \ with /. the problem has been solved

may I know the code how you resolve it...???
thanks

**Comment by PeymanBaghdadi** [comment]
> > I solved it, it was because of my path within annotation.txt and test_annotation.txt.
> > I should change last \ with /. the problem has been solved
> 
> may I know the code how you resolve it...???
> thanks

I just explained how do I resolve it!! where do you stuck?

**Comment by amaranth-andi** [comment]
sorry, that's problem already solved.
but, i got another problem here
FileNotFoundError: [Errno 2] No such file or directory: 'drive/My Drive/Colab Notebooks/FP/new/Faster_RCNN/model_vgg_config.pickle'
looks like it didn't find .pickle file there...
but the code said it's going to write on that location...

**Comment by PeymanBaghdadi** [comment]
> ther problem here
> FileNotFoundError: [Errno 2] No such file or directory: 'drive/My Drive/Colab Notebooks/FP/new/Faster_RCNN/model_vgg_config.pickle'

Check your paths, maybe your train code has some problem that can not make the .pickle file

**Comment by dherediat97** [comment]
Sorry for the delay, this is a problem that i had in other company, but i achieved with other [tutorial](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10) because this is imcomplete. I renember the ".pickle" file but with that i have other files and i need more files that the tutorial havent, i dont renember too much because it was like i said in other company with other computer, i havent any now...


The tutorial that i share is complete and anyone can create a model of tf of detection objects, this is real time, works perfect when compiled and save the model with videos or images.

Thanks @RockyXu66  for share this tutorial i learn too much with you! 👍
