### ISSUE TITLE
frcnn_train_vgg

### ISSUE THREAD

**Issue by amaranth-andi** [RockyXu66/Faster_RCNN_for_Open_Images_Dataset_Keras#56]
to @RockyXu66 thanks for the tutorial...
actually I got an error while executing frcnn_train_vgg, i already try it for a few times, but it still got the same error message and needs help to solve it.

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-24-d4748950189a> in <module>()
     13 
     14 # Save the configuration
---> 15 with open(config_output_filename, 'wb') as config_f:
     16         pickle.dump(C,config_f)
     17         print('Config has been written to {}, and can be loaded when testing to ensure correct results'.format(config_output_filename))

FileNotFoundError: [Errno 2] No such file or directory: 'drive/My Drive/Colab Notebooks/try_1/Faster_RCNN/model_vgg_config.pickle'

**Comment by PeymanBaghdadi** [comment]
Are you sure that you create the "drive/My Drive/Colab Notebooks/try_1/Faster_RCNN/" directory and also you need the below directory too. 
drive/My Drive/Colab Notebooks/try_1/Faster_RCNN/model/
important point is that this path is different from the original code, so you should change the paths in your customized code too.
